### ISSUE TITLE
Tambahkan Contoh untuk 3D

### ISSUE THREAD

**Issue by riizlaah** [renosyah/chunk_management_demo#1]
Bg, coba tambahin contoh implementasi buat 3D. Mau ku coba nanti
Terima Kasih

**Comment by renosyah** [comment]
done.

Uploading Screen_Recorder+_20240319090548.mp4…

**Comment by renosyah** [comment]
done.
https://github.com/renosyah/chunk_management_demo/assets/22163616/4bc1d0c0-3ea4-47d6-b2cd-8f6b5d4d0fdc
